layouts_dir: 'node_modules/abas-demo-site/dist'
baseurl: /react-day-input/

package_name: React Day Input
package_github_url: https://github.com/ABASystems/react-day-input
package_npm_url: https://www.npmjs.com/package/react-day-input
